name: ozzie
description: A new flutter package project.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_driver:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: 3.0.0

flutter:
